### ISSUE TITLE
Last updated value is unreliable

### ISSUE THREAD

**Issue by zfields** [blues/sparrow-reference-web-app#95]
![image](https://user-images.githubusercontent.com/2801887/167849749-216b475c-4892-4f88-8fa0-a8b488fe2f09.png)

The "Last updated" value is replicated across every sensor, and the value is incorrect. The latest reading I have from a sensor is 6:00a this morning according to the graph, but just above the graph it shows it was last updated two days ago.

This will be become a much bigger deal when I am trying to figure out which sensors are low on battery or have stopped reporting all together.

**Comment by paigen11** [comment]
This appears to be a known issue when using the Notehub API to pull data directly into the application instead of sending it to a third party database and pulling the data from there.

We'd recommend following the steps in the README.md to set up a local Postgres database for local development purposes and a cloud database for production purposes. That should resolve the issue you're seeing.
