### ISSUE TITLE
The values reported in the tiles, do not match the current values

### ISSUE THREAD

**Issue by zfields** [blues/sparrow-reference-web-app#98]
![image](https://user-images.githubusercontent.com/2801887/168085134-62cf281e-8a7b-45f5-8d68-b45f3a1feebb.png)

As you can see, the current temperature is 18.34C, but the tile is showing 33.31C.

_**EDIT:** I traced down the value, and it appears to come from May 9th @ 8:45:22 PM._

**Comment by paigen11** [comment]
This appears to be a known issue when using the Notehub API to pull data directly into the application instead of sending it to a third party database and pulling the data from there.

We'd recommend following the steps in the README.md to set up a local Postgres database for local development purposes and a cloud database for production purposes. That should resolve the issue you're seeing.
